### ISSUE TITLE
Triggering shaders changes from script-code

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#12]
Ok I checked the qfusion shader-manual and notices that it is actually quite a bit more advanced than the base q3 one, very nice!

So I would like to make a .iqm or md3 model that has a shader texture which includes some frames of texture animation, but similar to how you can do it with level entities, the shader swap to start the texture animations (or any other shader) should only be triggered on certain key presses (basically the movement keys). That way one could do cool animation supporting texture effects (like a glow only when the player moves or such) or make a 3D/2D pixel style hybrid model with a texture animation for the leg movement for example.

Is that somehow possible with the angelscript? Or is there some other way to do it in qfusion?

Besides that, I noticed that there is a shader function that allows alpha opacity according to view-angle. Is it feasible to make a sort of pseudo directional "sprite" with that by arranging some quads in a \* like manner and put that view-angle shader on them so that always only one of the quads is visible (e.g. the one that is facing more or less directly to the viewer).

**Comment by viciious** [comment]
No, it's not possible with AngelScript since AngelScript is only used for serverside gametype scripting and UI. I think what you want is passing some rendering flag or setting custom shader to an entity from cgame..

And no, that "alphagen dot" thing isn't really what you want and besides, it has been removed from the current codebase.
