### ISSUE TITLE
Making OpenGL 3.0 a minimal requirement

### ISSUE THREAD

**Issue by stopiccot** [Qfusion/qfusion#148]
I have an idea of making OpenGL 3.0 a mandatory requirement so we can remove all checks for extensions that were promoted to core in 3.0. (It's really weird to check for multitexturing or shader support in 2015). This will make code cleaner. We can stop using ARB suffixes in functions names. Eventually we can move to OpenGL 3.0 core profile. What do you think?

**Comment by Triang3l** [comment]
We will still need to check the support of OpenGL 3.0 features not present in OpenGL ES 2.0. Also I doubt this will make the overall code cleaner, only `r_register.c`.

**Comment by Triang3l** [comment]
It will make the code messier anyway as we will have to handle both enabling features (for newer extensions) and also _disabling_ them for GLES2 (depth textures, for instance) instead of simply enabling things when they're supported.

Anyway, we shouldn't do any refactoring if it doesn't benefit the players and can only potentially make the experience worse for them (in this specific case, make the game completely unplayable).

The game should work on as many configurations as possible, and if the game technically can be played, for example, on a system with GLSL support but no framebuffer blit, it must work on it, it shouldn't crash just because we wanted to shorten some function names.

We can get rid of the ARB suffixes using defines or different names for GetProcAddress and the QGL function pointers. I wanted to do this actually, but there are too many places where the suffixes are used, so I gave up as that wasn't important.

**Comment by mckaygerhard** [comment]
removing them made unportable to systems with linux maebo or low end machines but its decitions of u'rs

> The game should work on as many configurations as possible, and if the game technically can be played, for example, on a system with GLSL support but no framebuffer blit, it must work on it, it shouldn't crash just because we wanted to shorten some function names.

for example SDL2 does not are availabel for some linux ports due performance, and only propietary modules in X11 provide modern opengl extension

so the game will be GPL and depends on many non-gpl stuffs

**Comment by Triang3l** [comment]
What do you mean? We are _not_ making any modern extensions mandatory, only very old extensions like GLSL 1.20 and vertex buffers that have been available even in open drivers for a long time already. I was saying that we are trying to require as _less_ things as possible by using a GL1.1 context as the base, this seems to be the opposite of what you said in your comment.

**Comment by mckaygerhard** [comment]
thanks for clarify!
