### ISSUE TITLE
Improve cartoon outlines

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#17]
For now latest QF & WSW 1.03 have such outlines for Models & World:
![wsw_130905_223839](https://f.cloud.github.com/assets/4707112/1090719/9fea054c-165b-11e3-850d-4c8aea485488.jpg)
![wsw_130905_223807](https://f.cloud.github.com/assets/4707112/1090720/9fecdf56-165b-11e3-9e80-31942d59f012.jpg)
As you can see, there is a lot of glitches, especially at the corners & joints, lines have different width which depends on the distance from the viewpoint.

After experimeting with Xonotic, which uses DP engine, i've found 2 useful cmds:
r_celOutlines and r_celShading. The 1st one looks very cool, here is an example (i've used g_picmip 20 to make textures flat):
![xonotic20130905223101-00](https://f.cloud.github.com/assets/4707112/1090747/4ac0b6b4-165c-11e3-8950-c3489dd25cbc.jpg)
![xonotic20130905223144-00](https://f.cloud.github.com/assets/4707112/1090748/4ac60dc6-165c-11e3-8d15-764cb752f7db.jpg)
There are a few pitfalls - some places haven't outlines when they should, r_celOutline requires OpenGL 2.0.& it can cost some FPSes.

I'm not sure but that thread could be useful too - http://blenderartists.org/forum/showthread.php?172282-cartoon-in-GE/page2&highlight=Cartoon+in+BGE%3F

**Comment by viciious** [comment]
I’m closing this issue because it has been inactive for a while now. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with master branch. You can also contribute directly by providing a patch. :)

Thank you!
