### ISSUE TITLE
[SDL2] No output into Linux console after loading 

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#178]
I use to load the game via linux console from time to time. But now there is no output in it, it just starts the game w/o any single line. I'm pretty sure it is related to the SDL2, since making a build with that line commented out https://github.com/Warsow/qfusion/blob/44f5d262f2fd8bdac9d747b5593d877dedd09633/source/CMakeLists.txt#L159 solves the problem.

Happens only with qfusion binary, qfusion_server and qfusiontv_server do spam linux console as they should.

**Comment by viciious** [comment]
Assigning to @stopiccot

**Comment by stopiccot** [comment]
Yeah, such issue exists because some functions are still not implemented for SDL2. And I decided not to use current versions because they are kinda messy and inconsistent. For example `Sys_ConsoleOutput` checks for `dedicated` convar on windows platform, but on unix platform it checks for `nostdout` instead. So it would be really great to make some specification how things should work first.

**Comment by stopiccot** [comment]
- nostdout, nostdout_backup_val, console_textlen?
- why console output is disabled for dedicated server on windows platform?

**Comment by viciious** [comment]
> why console output is disabled for dedicated server on windows platform?

Guess it would mess up console commands typing.

**Comment by stopiccot** [comment]
Only on Windows?

**Comment by viciious** [comment]
Typing commands in linux console never worked.

**Comment by hettoo** [comment]
So... can we just use the platform-specific code here also in the case of SDL? I don't think SDL should be responsible for console output.

For some debugging cases it would certainly be nice to have console output.

(I would try this myself, but I am a noob with cmake :p and I can't test the Windows part anyway.)

Edit: ehh, it says I unassigned stoppicot, but I didn't do such a thing... :s
