### ISSUE TITLE
qfusion version scheme?

### ISSUE THREAD

**Issue by mckaygerhard** [Qfusion/qfusion#257]
theres's any version scheme or what are the version of qfusion ..

this for packagin for other linux distros and make it available as quake2 engine too

**Comment by Triang3l** [comment]
There isn't version numbering because it gets lots of updates very often. Also Qfusion code in this repository is the upstream Warsow code, with some differences in version.h, so you may consider Warsow versions Qfusion versions as well.

Qfusion itself has zero use as a Linux package separately from a game, also making a non-Warsow game on it would most likely require many changes in the engine code itself (starting from version.h at least).

Qfusion supports almost none of Quake 2 file formats, it's hasn't been a Quake 2 engine for a long time, it's just Warsow engine now.

**Comment by mckaygerhard** [comment]
so i'll close this issue with those conclusions:

1) warson/qfusion it's not qfusion, iths a specific warson engine
2) version scheme its the warso0n version scheme when warson are release
3) warson/qfusion does not work with any quake formats (officially)

thanks. Please added those to the README.md as important info.

**Comment by Triang3l** [comment]
Qfusion is general-purpose, but definitely not as general-purpose as Unity, for example. You will have to modify engine's renderer itself to add new shader effects, for instance.

Qfusion supports Quake 3 formats (though it's very recommended to use IQM for players rather than MD3, for example, or compile maps specifically for Warsow with better lighting), but not Quake 2.

**Comment by mckaygerhard** [comment]
?!, wow, qfusion supports quake3 maps but not quake2, and supports quake ? data games from?

in any case, thank for calrify. as i said may be ussefully added that to README.md

**Comment by Triang3l** [comment]
No, Quake 1 and 2 map support was removed in 1.5.

**Comment by mckaygerhard** [comment]
i have a question, where i can downloads of older releases of warzone, by ex. previously to 1.5 release?

**Comment by adem4ik** [comment]
1) http://www.moddb.com/games/warsow/downloads "SDK" = engine sources
2) its name is WARSOW, not WARZONE

**Comment by mckaygerhard** [comment]
oh thanks, sdk are the sources and the others are the game complete..

i like to know how to generate the game data from sources but for now its good, thanks.

**Comment by adem4ik** [comment]
there are no public sources for warsow game data, as it comes under proprietary license, in other words only engine is GPLed.

**Comment by mckaygerhard** [comment]
thanks, ok
