### ISSUE TITLE
Awards are not reset on demojumps

### ISSUE THREAD

**Issue by adem4ik** [Qfusion/qfusion#319]
Precondition: cg_showAwards 1 (default value)

1) Download the demo [duel_2016-03-23_20-46_wdm2_adem(3russia_(1-57 rails).wdz20.zip](https://github.com/Warsow/qfusion/files/190463/duel_2016-03-23_20-46_wdm2_adem.3russia_.1-57.rails.wdz20.zip)
2) Open it in Warsow
3) demojump 490
4) Wait till the frag happens on 1:51 (timer counts down)
5) demojump -10
6) Wait till the frag happens on 1:51 once more
7) Repeat 5-6

Result: ![wsw_award](https://cloud.githubusercontent.com/assets/4707112/14059844/fb7faab2-f360-11e5-9b1f-b13f57520cdc.png)

Note: There was same bug with obituaries, which was fixed somewhere in 1.0-1.5

**Comment by hettoo** [comment]
Try changing cg.time to cg.realTime in these lines:

$ git grep -n cg.award_times source/
source/cgame/cg_cmds.cpp:865:   cg.award_times[cg.award_head % MAX_AWARD_LINES] = cg.time;
source/cgame/cg_hud.cpp:1166:           if( cg.award_times[current % MAX_AWARD_LINES] + MAX_AWARD_DISPLAYTIME < cg.time )
source/cgame/cg_hud.cpp:1190:           moveTime = ( cg.time - cg.award_times[ current ] ) / 1000.0f;

(Sorry for being lazy, but I need to be doing other things. :p)

**Comment by hettoo** [comment]
I think centerprints are affected in the same way.
(Edit: no, there was just a useless assignment distracting me. Various cgame effects I expect could exhibit similar glitches, however.)

One more quick note, though, is that ideally we would use a variation of realTime that is aware of the current timescale. Otherwise, the effect can become very brief in movies. A realTime reference is already used for the chat area, and you see in this video that text there fades very quickly: https://www.youtube.com/watch?v=FBMW9SkG_hE&t=20

**Comment by adem4ik** [comment]
> Try changing cg.time to cg.realTime in these lines:
> 
> $ git grep -n cg.award_times source/
> source/cgame/cg_cmds.cpp:865: cg.award_times[cg.award_head % MAX_AWARD_LINES] = cg.time;
> source/cgame/cg_hud.cpp:1166: if( cg.award_times[current % MAX_AWARD_LINES] + MAX_AWARD_DISPLAYTIME < cg.time )
> source/cgame/cg_hud.cpp:1190: moveTime = ( cg.time - cg.award_times[ current ] ) / 1000.0f;

checked, it fixes the issue

**Comment by viciious** [comment]
Hopefully fixed in 6f0e434

**Comment by viciious** [comment]
On a side note, there's no need to zip-archive .wdz20 files: they're gzip-compressed already
