### ISSUE TITLE
Refactor game networking protocol

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#373]
The PS_M_* and U_ bits stuff in qcommon.h and msg.c is difficult to extend and maintain. The necessity to spare bits in delta encoding promoted the introduction of ugly nameless unions in entity_state_t. This needs to be fixed once and for all.

**Comment by dnk777** [comment]
I think a real aim is to allow scripts write/read entity state from bit streams as they wish (even Quake I does this) with getting rid of the god `edict_t` struct and run the same gametype script on client and server together (like Unreal does) to allow scripting custom network-updated entities. Look at how particles are transimtted in the current state.

https://github.com/Qfusion/qfusion/blob/master/source/game/g_frame.cpp#L361

Useful parts of `edict_t` should be extracted and exposed for scripts like `PhysicsState`, etc.

This, however, aside from huge code overhaul requires a decent AS jit support, because AS scripts as-is are really slow.

**Comment by viciious** [comment]
I'm not following you, what exactly does Quake1 allow?

**Comment by viciious** [comment]
Ah, you probably mean the fact that MSG_ functions are exported to QuakeC progs. Which wasn't such a great in my opinion, because the client-side part was coded in C anyway.

**Comment by viciious** [comment]
Partially addressed in 82ce50b5a437020c8dba83c4e78ee2fa3a098e6b

**Comment by dnk777** [comment]
Let me show an example. What if i code a custom tutorial gametype and want to show my custom strafehud + several marks on screen in the specific area of a map? Currently this can't be done without modifying client native code.

Ideally the same script should run simultaneously on client and server (there should be either null-implementations for non-active on this type of network peer (client or server) code or such code might be marked in AS via attributes). A network replication of an arbitrary script object would be sweet (it can be done either by exposing bit delta IO streams to scripts or marking replicated script fields via attributes and building a script struct replication map for the script object type reflecting these attributes before script start). 

This means cgame should be scripted as well. The problem is not only that intoduction of it requires a major codebase overhaul but in that scripts are very slow, and given the performance requirements for client code this can't be done unless a very efficient JIT is available for all target platforms.

**Comment by viciious** [comment]
I don't think that angelscript performance is a legitimate concern at all as far as client-side scripting goes

**Comment by viciious** [comment]
More or less resolved (see msg.c)
