### ISSUE TITLE
Code defects in the AI code

### ISSUE THREAD

**Issue by viciious** [Qfusion/qfusion#395]
Coverity has detected newly introduced defects in the AI code. @dnk777 Please investigate.

https://gist.github.com/viciious/78f9d10145bdf8ba74ec3669f108e1b8

**Comment by dnk777** [comment]
I have just looked at it. I will give a comment and a possible fix for each warning soon.

**Comment by viciious** [comment]
https://gist.github.com/viciious/b850dfb0d8fbaf2886d1fe379aa9ec95

**Comment by viciious** [comment]
I'm going to need your email address for you to be able to join the coverity project. There's more issues with the AI code out there..

**Comment by dnk777** [comment]
Ok I have an access now. Though most of issues from the first look are not really harmful as I have explained (such as variables falsely indicated as uninitialized due to limited control flow analysis depth), there are some pretty lame bugs. I will fix all these issues along with the promised patches.

**Comment by dnk777** [comment]
This definition in `gameshared/gs_public.h` yields warnings in each site where it is used:

```
#define DEFAULT_PLAYERSPEED ( GS_RaceGametype() ? DEFAULT_PLAYERSPEED_RACE \
: ( GS_Instagib() ? DEFAULT_PLAYERSPEED_INSTAGIB : DEFAULT_PLAYERSPEED_STANDARD ) )
```

since all partial `DEFAULT_PLAYERSPEED_*` values equal `320.0f`.

**Comment by dnk777** [comment]
I think we should either get rid of these partial definitions or set slightly different values for each one (like `320.000f`, `320.001f`).

**Comment by viciious** [comment]
It is possible to mark that specific spot as a false positive but let's not concern ourselves with this for the moment.

**Comment by viciious** [comment]
Please see https://github.com/Qfusion/qfusion/commit/c42c7aed347835707f6e2c4cd9c42d2ad158cc18#commitcomment-23378522

**Comment by dnk777** [comment]
There are 6 issues left (or newly discovered? I'm sure I tried fixing all issues in the list).
2 issues (IDENTICAL_BRANCHES) are related to the mentioned `DEFAULT_PLAYERSPEED` macro.
2 issues (MIXED_ENUMS) are annoying... not sure how they should be mitigated (probably cast an integer tag to a enum explicitly instead of casting a enum to an integer).
2 are minor (I'm pretty sure they weren't shown in the previous analysis results).
I will fix these 4 issues of course.

**Comment by viciious** [comment]
Ignore the MIXED_ENUMS one, the code is totally legit.

**Comment by dnk777** [comment]
Can also this annoying warning about `rand()` being non-secure be turned off? If so it is possible to have no issues in the AI code at all after the final fix.
