### ISSUE TITLE
Weather effects

### ISSUE THREAD

**Issue by poVoq** [Qfusion/qfusion#7]
Not sure how different the also idTech2 based engine from AlienArena is, but this kind of particle weather effects might be nice to have in qfusion too:
http://www.youtube.com/watch?v=qm2fNneKwYo

Or is it already possible but undocumented?

**Comment by viciious** [comment]
Guess this particular particle code might be ported from AA in a straighforward manner but I have no intention of doing that whatsoever. If you provide me with a clean patch I'll merge it.

**Comment by poVoq** [comment]
Well sorry if I sound too demanding... I am not really able to do so myself. I am lucky if I manage to do some game-type scripting :-/

What are your plans for qfusion anyways? Sound a bit like you are calling it more or less "done", which would be a pity.

**Comment by viciious** [comment]
Somehow I feel you won't progress too far with your potential game with engine alone and no coding skills.

As for the features and my plans, I just do whatever I feel inspired to do and when I have the time for some coding. This is how it has always been.

**Comment by poVoq** [comment]
Ok understandable.

Regarding my maybe potentially happening game... well you might be right, but I don't have overly ambitious goals and do know my way around the artistic side of things quite well.

**Comment by viciious** [comment]
I’m closing this issue because it has been inactive for a while now. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with master branch. You can also contribute directly by providing a patch. :)

Thank you!
